import { and, eq, sql } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/db";
import { events, timeSlots } from "@/db/schema";
import { requireAdminApi } from "@/lib/admin-guard";
import { saveSpeakerPhoto } from "@/lib/uploads";
import { participantRoles } from "@/lib/validation";

const fields = z.object({ timeSlotId: z.coerce.number().int().positive(), title: z.string().trim().min(2).max(250), description: z.string().trim().min(2).max(10000), speakerName: z.string().trim().min(2).max(150), room: z.string().trim().max(100), capacity: z.coerce.number().int().min(0).max(100000), sortOrder: z.coerce.number().int().min(0).max(10000), registrationOpen: z.enum(["true", "false"]).transform(value => value === "true") });
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { const guard = await requireAdminApi(); if (guard instanceof NextResponse) return guard; const id = Number((await params).id); if (!Number.isInteger(id)) return NextResponse.json({ message: "Некорректный идентификатор." }, { status: 400 }); try { const data = await request.formData(); const parsed = fields.safeParse(Object.fromEntries(data)); const allowedRoles=data.getAll("allowedRoles").filter((role):role is typeof participantRoles[number]=>typeof role==="string"&&participantRoles.includes(role as typeof participantRoles[number])); if (!parsed.success||!allowedRoles.length) return NextResponse.json({ message: "Заполните поля и выберите хотя бы одну роль." }, { status: 400 }); const current = (await db.select().from(events).where(eq(events.id, id)).limit(1))[0]; if (!current) return NextResponse.json({ message: "Мероприятие не найдено." }, { status: 404 }); const slot = (await db.select({ conferenceId: timeSlots.conferenceId }).from(timeSlots).where(eq(timeSlots.id, parsed.data.timeSlotId)).limit(1))[0]; if (!slot || slot.conferenceId !== current.conferenceId) return NextResponse.json({ message: "Слот должен относиться к той же конференции." }, { status: 422 }); if (parsed.data.capacity < current.bookedCount) return NextResponse.json({ message: "Вместимость не может быть меньше числа занятых мест." }, { status: 422 }); const photo = await saveSpeakerPhoto(data.get("speakerPhoto") as File | null); await db.update(events).set({ ...parsed.data, allowedRoles, room: parsed.data.room || null, speakerPhotoPath: photo ?? current.speakerPhotoPath, updatedAt: new Date() }).where(eq(events.id, id)); return NextResponse.redirect(new URL("/admin/events?updated=1", request.url), 303); } catch (error) { const message = error instanceof Error ? error.message : "Не удалось сохранить мероприятие."; return NextResponse.json({ message }, { status: 500 }); } }
