import { and, asc, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/db";
import { conferences, events, timeSlots } from "@/db/schema";
import { requireAdminApi } from "@/lib/admin-guard";
import { saveSpeakerPhoto } from "@/lib/uploads";
import { participantRoles } from "@/lib/validation";

const eventFields = z.object({ timeSlotId: z.coerce.number().int().positive(), title: z.string().trim().min(2).max(250), description: z.string().trim().min(2).max(10000), speakerName: z.string().trim().min(2).max(150), room: z.string().trim().max(100), capacity: z.coerce.number().int().min(0).max(100000), sortOrder: z.coerce.number().int().min(0).max(10000), registrationOpen: z.enum(["true", "false"]).transform(value => value === "true") });

export async function GET() { const guard = await requireAdminApi(); if (guard instanceof NextResponse) return guard; const rows = await db.select({ id: events.id, title: events.title, description: events.description, speakerName: events.speakerName, speakerPhotoPath: events.speakerPhotoPath, room: events.room, capacity: events.capacity, bookedCount: events.bookedCount, registrationOpen: events.registrationOpen, sortOrder: events.sortOrder, timeSlotId: timeSlots.id, slotTitle: timeSlots.title }).from(events).innerJoin(timeSlots, eq(events.timeSlotId, timeSlots.id)).orderBy(asc(timeSlots.sortOrder), asc(events.sortOrder)); return NextResponse.json(rows); }
export async function POST(request: Request) { const guard = await requireAdminApi(); if (guard instanceof NextResponse) return guard; try { const data = await request.formData(); const parsed = eventFields.safeParse(Object.fromEntries(data)); const allowedRoles=data.getAll("allowedRoles").filter((role):role is typeof participantRoles[number]=>typeof role==="string"&&participantRoles.includes(role as typeof participantRoles[number])); if (!parsed.success||!allowedRoles.length) return NextResponse.json({ message: "Заполните поля и выберите хотя бы одну роль." }, { status: 400 }); const slot = (await db.select({ conferenceId: timeSlots.conferenceId }).from(timeSlots).where(eq(timeSlots.id, parsed.data.timeSlotId)).limit(1))[0]; if (!slot) return NextResponse.json({ message: "Временной слот не найден." }, { status: 422 }); const photo = await saveSpeakerPhoto(data.get("speakerPhoto") as File | null); const event = (await db.insert(events).values({ ...parsed.data, allowedRoles, conferenceId: slot.conferenceId, speakerPhotoPath: photo, room: parsed.data.room || null }).returning({ id: events.id }))[0]; return NextResponse.redirect(new URL(`/admin/events?created=${event.id}`, request.url), 303); } catch (error) { const message = error instanceof Error ? error.message : "Не удалось создать мероприятие."; return NextResponse.json({ message }, { status: 500 }); } }
